-- =============================================================================
-- Migration 007: Add primary_supplier_id to sku_master and create
--                reorder_recommendations table.
--
-- Run this in the Supabase SQL Editor before using engine/reorder.py.
-- Safe to re-run — all operations use IF NOT EXISTS / IF NOT EXISTS guards.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add primary_supplier_id to sku_master
--    Populated by the data team or via partswatch_pull when real exports
--    contain a preferred-supplier field.  NULL = fallback to most recent PO.
-- ---------------------------------------------------------------------------
ALTER TABLE sku_master
    ADD COLUMN IF NOT EXISTS primary_supplier_id VARCHAR(50);

COMMENT ON COLUMN sku_master.primary_supplier_id IS
    'Preferred supplier for reorder routing.  NULL → engine falls back to '
    'most recent purchase_orders entry for this SKU.';

CREATE INDEX IF NOT EXISTS idx_sku_primary_supplier
    ON sku_master (primary_supplier_id)
    WHERE primary_supplier_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. reorder_recommendations — one row per (SKU, location, recommendation date)
--    Generated nightly by engine/reorder.py.  Purchasing team sets is_approved.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reorder_recommendations (
    id                       BIGSERIAL       PRIMARY KEY,

    -- What to order and where
    sku_id                   VARCHAR(50)     NOT NULL REFERENCES sku_master(sku_id),
    location_id              VARCHAR(20)     NOT NULL,
    recommendation_date      DATE            NOT NULL,

    -- Order sizing
    qty_to_order             NUMERIC(12,4)   NOT NULL,
    supplier_id              VARCHAR(50),

    -- Transfer vs external PO
    recommendation_type      VARCHAR(10)     NOT NULL
                                 CHECK (recommendation_type IN ('po', 'transfer')),
    transfer_from_location   VARCHAR(20),    -- source location when type = 'transfer'

    -- Inventory position at time of recommendation
    days_of_supply_remaining NUMERIC(10,2),  -- capped at 9999.99 for infinite (zero demand)

    -- Urgency tier
    urgency                  VARCHAR(10)     NOT NULL
                                 CHECK (urgency IN ('critical', 'warning', 'normal')),

    -- Forecast provenance
    forecast_model_used      VARCHAR(20),

    -- Supplier risk at time of recommendation
    supplier_risk_flag       VARCHAR(10)
                                 CHECK (supplier_risk_flag IN ('green', 'amber', 'red')),

    -- Approval workflow
    is_approved              BOOLEAN         NOT NULL DEFAULT FALSE,
    approved_by              VARCHAR(100),
    approved_at              TIMESTAMPTZ,

    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- One recommendation per SKU + location per day.  Re-runs on the same day
    -- are ignored (ignored on conflict) to preserve approval state.
    UNIQUE (sku_id, location_id, recommendation_date)
);

CREATE INDEX IF NOT EXISTS idx_reorder_sku_id
    ON reorder_recommendations (sku_id);
CREATE INDEX IF NOT EXISTS idx_reorder_location
    ON reorder_recommendations (location_id);
CREATE INDEX IF NOT EXISTS idx_reorder_date
    ON reorder_recommendations (recommendation_date);
CREATE INDEX IF NOT EXISTS idx_reorder_urgency
    ON reorder_recommendations (urgency);
CREATE INDEX IF NOT EXISTS idx_reorder_type
    ON reorder_recommendations (recommendation_type);
CREATE INDEX IF NOT EXISTS idx_reorder_approved
    ON reorder_recommendations (is_approved) WHERE is_approved = FALSE;
CREATE INDEX IF NOT EXISTS idx_reorder_supplier
    ON reorder_recommendations (supplier_id)
    WHERE supplier_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reorder_sku_date
    ON reorder_recommendations (sku_id, recommendation_date);

COMMENT ON TABLE reorder_recommendations IS
    'Nightly reorder and transfer recommendations generated by engine/reorder.py. '
    'Purchasing team reviews and sets is_approved = TRUE each morning.';
