-- =============================================================================
-- Migration 008: Create alerts table for the morning dashboard feed.
--
-- Run this in the Supabase SQL Editor before using engine/alerts.py.
-- Safe to re-run — CREATE TABLE IF NOT EXISTS + IF NOT EXISTS indexes.
-- =============================================================================

CREATE TABLE IF NOT EXISTS alerts (
    id               BIGSERIAL    PRIMARY KEY,

    -- When this alert was generated
    alert_date       DATE         NOT NULL,

    -- Alert classification
    alert_type       VARCHAR(40)  NOT NULL
                         CHECK (alert_type IN (
                             'CRITICAL_STOCKOUT',
                             'LOW_SUPPLY',
                             'FREEZE_ALERT',
                             'SUPPLIER_RISK',
                             'DEAD_STOCK',
                             'TRANSFER_OPPORTUNITY',
                             'FORECAST_ACCURACY_DROP'
                         )),
    severity         VARCHAR(10)  NOT NULL
                         CHECK (severity IN ('critical', 'warning', 'info')),

    -- Optional context — all nullable (some alerts are class- or supplier-level)
    sku_id           VARCHAR(50)  REFERENCES sku_master(sku_id),
    location_id      VARCHAR(20),
    supplier_id      VARCHAR(50),

    -- Human-readable alert text shown on the dashboard
    message          TEXT         NOT NULL,

    -- Deterministic composite key used to prevent duplicate alerts on the
    -- same day for the same issue.  Format varies by alert_type but is
    -- always {ALERT_TYPE}|{context...}.  Nullable FK columns cannot form
    -- a UNIQUE index reliably in PostgreSQL (NULLs are distinct), so we
    -- encode the identifying fields into this single VARCHAR column.
    alert_key        VARCHAR(250) NOT NULL,

    -- Acknowledgement workflow — set by the purchasing/ops team
    is_acknowledged  BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_by  VARCHAR(100),
    acknowledged_at  TIMESTAMPTZ,

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- One alert per (date, key) — re-runs on the same day are ignored so
    -- acknowledgements are never overwritten.
    UNIQUE (alert_date, alert_key)
);

CREATE INDEX IF NOT EXISTS idx_alerts_date
    ON alerts (alert_date DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_type
    ON alerts (alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_severity
    ON alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alerts_sku_id
    ON alerts (sku_id) WHERE sku_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_alerts_supplier_id
    ON alerts (supplier_id) WHERE supplier_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_alerts_unacked
    ON alerts (is_acknowledged, alert_date DESC)
    WHERE is_acknowledged = FALSE;

COMMENT ON TABLE alerts IS
    'Nightly alert feed generated by engine/alerts.py.  '
    'Surfaced on the morning dashboard for purchasing and operations teams.';

COMMENT ON COLUMN alerts.alert_key IS
    'Pipe-delimited composite string encoding the uniqueness of each alert. '
    'Format: {ALERT_TYPE}|{field1}|{field2}... — prevents duplicate alerts '
    'on the same day for the same underlying issue.';

-- Disable RLS (consistent with all other tables in this project)
ALTER TABLE alerts DISABLE ROW LEVEL SECURITY;
