-- =============================================================================
-- Migration 009: Location classification and demand quality scoring.
--
-- Run this in the Supabase SQL Editor before using
-- transform/location_classify.py.  Safe to re-run — all IF NOT EXISTS.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1.  Add is_residual_demand column to sales_transactions
--     Flagged by location_classify.py when a sales spike coincides with
--     simultaneous stockouts at other locations (third-call demand pattern).
--     Excluded from forecast training in both forecast_rolling.py and
--     forecast_lgbm.py, same as is_anomaly = TRUE.
-- ---------------------------------------------------------------------------
ALTER TABLE sales_transactions
    ADD COLUMN IF NOT EXISTS is_residual_demand BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_sales_residual
    ON sales_transactions (is_residual_demand)
    WHERE is_residual_demand = TRUE;

COMMENT ON COLUMN sales_transactions.is_residual_demand IS
    'TRUE when this sale is classified as residual / third-call demand '
    '(a spike correlated with simultaneous stockouts at peer locations). '
    'Excluded from forecast training data by location_classify.py.';


-- ---------------------------------------------------------------------------
-- 2.  locations table — one row per location; stores tier classification and
--     the normalised component scores used to derive the tier.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
    location_id           VARCHAR(20)   PRIMARY KEY,

    -- Tier 1 = first-call, Tier 2 = second-call, Tier 3 = third-call
    location_tier         SMALLINT      NOT NULL
                              CHECK (location_tier IN (1, 2, 3)),

    -- Normalised component scores (0.0 – 1.0), computed during classification
    fill_rate_score       NUMERIC(6, 4) NOT NULL,
    revenue_score         NUMERIC(6, 4) NOT NULL,
    sku_breadth_score     NUMERIC(6, 4) NOT NULL,
    return_rate_score     NUMERIC(6, 4) NOT NULL,  -- inverted: lower returns = higher score

    -- Weighted composite of the four components
    composite_tier_score  NUMERIC(6, 4) NOT NULL,

    classified_date       DATE          NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_locations_tier
    ON locations (location_tier);

COMMENT ON TABLE locations IS
    'Location performance tier classifications generated by '
    'transform/location_classify.py.  '
    'Tier 1 = first-call, Tier 2 = second-call, Tier 3 = third-call.';


-- ---------------------------------------------------------------------------
-- 3.  sku_location_demand_quality — one row per (SKU, location) pair.
--     Stores the demand quality score (0.0 to 1.0) used as a LightGBM
--     feature and to weight Tier 3 forecasts toward the regional average.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sku_location_demand_quality (
    sku_id                VARCHAR(50)   NOT NULL REFERENCES sku_master(sku_id),
    location_id           VARCHAR(20)   NOT NULL,

    -- 1.0 = fully organic demand; 0.0 = 100 % residual / third-call demand
    demand_quality_score  NUMERIC(4, 3) NOT NULL
                              CHECK (demand_quality_score BETWEEN 0.0 AND 1.0),

    organic_sale_count    INTEGER       NOT NULL DEFAULT 0,
    residual_sale_count   INTEGER       NOT NULL DEFAULT 0,
    total_sale_count      INTEGER       NOT NULL DEFAULT 0,

    classified_date       DATE          NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    PRIMARY KEY (sku_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_sku_loc_dq_location
    ON sku_location_demand_quality (location_id);
CREATE INDEX IF NOT EXISTS idx_sku_loc_dq_score
    ON sku_location_demand_quality (demand_quality_score);

COMMENT ON TABLE sku_location_demand_quality IS
    'Per-SKU per-location demand quality scores computed by '
    'transform/location_classify.py.  '
    'Scores < 0.5 indicate primarily residual (third-call) demand and '
    'trigger regional-average blending in the forecast models.';

COMMENT ON COLUMN sku_location_demand_quality.demand_quality_score IS
    '1.0 = consistently organic demand.  '
    '0.5 = mixed organic/residual.  '
    '0.0 = entirely residual (only sells when peer locations are stocked out).';


-- ---------------------------------------------------------------------------
-- 4.  Disable RLS on new tables (consistent with all other tables in project)
-- ---------------------------------------------------------------------------
ALTER TABLE locations                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE sku_location_demand_quality DISABLE ROW LEVEL SECURITY;
