-- =============================================================================
-- Migration 011: Forecast accuracy tracking
--
-- Adds columns to forecast_results for back-testing, creates accuracy_reports
-- summary table, and adds accuracy_score to sku_master.
--
-- Run in the Supabase SQL Editor.  Safe to re-run.
-- =============================================================================

-- 1. Add actual vs predicted columns to forecast_results
ALTER TABLE forecast_results
    ADD COLUMN IF NOT EXISTS actual_qty_sold NUMERIC(12,4),
    ADD COLUMN IF NOT EXISTS mape_error      NUMERIC(8,4);

CREATE INDEX IF NOT EXISTS idx_forecast_actual_filled
    ON forecast_results (forecast_date)
    WHERE actual_qty_sold IS NOT NULL;

-- 2. Accuracy reports — weekly summary by model × abc_class
CREATE TABLE IF NOT EXISTS accuracy_reports (
    id                       BIGSERIAL     PRIMARY KEY,
    report_date              DATE          NOT NULL,
    model_type               VARCHAR(20)   NOT NULL,
    abc_class                VARCHAR(1)    NOT NULL,
    avg_mape                 NUMERIC(8,2)  NOT NULL,
    avg_mae                  NUMERIC(12,4) NOT NULL,
    bias                     NUMERIC(12,4) NOT NULL,
    hit_rate_20pct           NUMERIC(5,2)  NOT NULL,
    total_forecasts_evaluated INTEGER      NOT NULL,
    sku_count                INTEGER       NOT NULL,
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    UNIQUE (report_date, model_type, abc_class)
);

CREATE INDEX IF NOT EXISTS idx_accuracy_reports_date
    ON accuracy_reports (report_date DESC);

COMMENT ON TABLE accuracy_reports IS
    'Weekly forecast accuracy summary generated by ml/accuracy.py. '
    'One row per (report_date, model_type, abc_class) combination.';

-- 3. Per-SKU accuracy score in sku_master
ALTER TABLE sku_master
    ADD COLUMN IF NOT EXISTS accuracy_score NUMERIC(8,2);

COMMENT ON COLUMN sku_master.accuracy_score IS
    'Rolling 4-week MAPE for this SKU across all models. '
    'High values flag SKUs where forecasting struggles.';

-- 4. Disable RLS on new table
ALTER TABLE accuracy_reports DISABLE ROW LEVEL SECURITY;
